### ISSUE TITLE
Some minimal documentation is deeply needed

### ISSUE THREAD

**Issue by NaLiJa** [thm-projects/arsnova-flashcards#5]
Looks like a fantastic system and I got it to install on a Debian machine, but without some docs about customization it is practically impossible to use the system after install, e.g. there are no hints how to use some other form of login instead of the THM CAS Login...

**Comment by ghost** [comment]
Hello,

a documentation for the settings will follow during this summer.

To activate a login on the landingpage, you have to adjust the "login" area for defaultSettings under ```imports/config/server.js``` and enter the settings for the corresponding login in your settings.json.

**Comment by NaLiJa** [comment]
Thanks!
